name: Linting

on:
  push:

jobs:
  lint:
    name: Linting Test
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies (Yarn)
        run: yarn install
      - name: Lint with ESLint and Prettier
        run: yarn lint
      - name: CRLF Phobia
        run: yarn dlx crlf-phobia *
